casa variety scripts

diff --git a/config/variety/scripts/set_wallpaper_arco b/config/variety/scripts/set_wallpaper_arco
--- a/config/variety/scripts/set_wallpaper_arco
+++ b/config/variety/scripts/set_wallpaper_arco
@@ -18,6 +18,12 @@
 #
 # $3: The third passed parameter is the absolute path to the original wallpaper image (before effects, clock, etc.)
 #
+# $4: Fourth parameter comes from the display mode setting: "os" means that set_wallpaper should try to
+# leave the OS setting unchanged. "zoom" means to try to fill the screen fully with the provided image.
+# Other parameters that could be passed are the scaling modes used by GNOME:
+# "centered", "scaled", "stretched", "zoom", "spanned", "wallpaper"
+# TODO: Ideally all sections below for different DEs would take this setting into account
+#
 # EXAMPLE:
 # echo "$1" # /home/username/.config/variety/wallpaper/wallpaper-clock-fac0eef772f9b03bd9c0f82a79d72506.jpg
 # echo "$2" # auto
@@ -120,38 +126,29 @@ fi
 # and KDE will refresh it
 # On Plasma 5.7 and above, the wallpaper choosing is automatic.
 if [ "${KDE_FULL_SESSION}" == "true" ]; then
-    # Plasma 5.7 introduced a new feature to set the wallpaper via a qdbus script:
+    # Plasma 5.7 introduced a new feature to set the wallpaper via a dbus script:
     # https://github.com/KDE/plasma-workspace/commit/903cbfd7e267a4812a6ec222eb7e1b5dd775686f
     if [[ -n "${KDE_SESSION_VERSION}" && "${KDE_SESSION_VERSION}" == '5' ]]; then
-
-        # Try to find the Qt 5 version of qdbus. For systems using qtchooser, the binary name is 'qdbus'
-        # and the Qt version can be selected via the QT_SELECT environment variable.
-        if command -v qdbus-qt5 &>/dev/null; then
-            qdbus_command=qdbus-qt5
-        else
-            qdbus_command=qdbus
-        fi
-
-        QT_SELECT=5 $qdbus_command org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript "
-        var allDesktops = desktops();
-        for (i=0; i < allDesktops.length; i++) {
-            d = allDesktops[i];
-            d.wallpaperPlugin = 'org.kde.image';
-            d.currentConfigGroup = Array('Wallpaper', 'org.kde.image', 'General');
-            d.writeConfig('Image', 'file://""$WP""')
+        dbus-send --type=method_call --dest=org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript string:"
+        let allDesktops = desktops();
+        for (let d of allDesktops) {
+            if (d.wallpaperPlugin == 'org.kde.image') {
+                d.currentConfigGroup = Array('Wallpaper', 'org.kde.image', 'General');
+                d.writeConfig('Image', 'file://""$WP""')
+            }
         }
         "
-        # Reuse the exit code from qdbus
-        qdbus_exitcode="$?"
+        # Reuse the exit code from dbus
+        dbus_exitcode="$?"
 
-        if [[ "$qdbus_exitcode" -ne 0 ]]; then
+        if [[ "$dbus_exitcode" -ne 0 ]]; then
             # If the script fails, show a notification.
             kdialog --title "Variety: cannot change Plasma wallpaper" --passivepopup "Could not change the Plasma 5 wallpaper; \
                 make sure that you're using Plasma 5.7+ and have widgets unlocked.\n----\n \
                 Due to Plasma limitations, external programs cannot automatically change the wallpaper when the widgets are locked.\n \
                 See https://git.io/vprpM for more information." --icon variety 10  # Final number is the length of the popup
         fi
-        exit "$qdbus_exitcode"
+        exit "$dbus_exitcode"
 
     else
         WALLDIR="$(xdg-user-dir PICTURES)/variety-wallpaper"
@@ -168,20 +165,28 @@ fi
 # Gnome 3, Unity
 gsettings set org.gnome.desktop.background picture-uri "file://$WP" 2> /dev/null
 gsettings set org.gnome.desktop.background picture-uri-dark "file://$WP" 2> /dev/null
-if [ "$(gsettings get org.gnome.desktop.background picture-options)" == "'none'" ]; then
+if [[ "$4" =~ ^(wallpaper|centered|scaled|stretched|zoom|spanned)$ ]]; then
+    gsettings set org.gnome.desktop.background picture-options "$4"
+fi
+if [ "$(gsettings get org.gnome.desktop.background picture-options)" == "'none'"  ]; then
     gsettings set org.gnome.desktop.background picture-options 'zoom'
 fi
 
 # GNOME Screensaver / Lock screen - thanks to George C. de Araujo for the patch
 gsettings set org.gnome.desktop.screensaver picture-uri "file://$WP" 2> /dev/null
+if [[ "$4" =~ ^(wallpaper|centered|scaled|stretched|zoom|spanned)$ ]]; then
+    gsettings set org.gnome.desktop.screensaver picture-options "$4"
+fi
 if [ "$(gsettings get org.gnome.desktop.screensaver picture-options)" == "'none'" ]; then
     gsettings set org.gnome.desktop.screensaver picture-options 'zoom'
 fi
 
-
 # Deepin
 if [ "$(gsettings list-schemas | grep -c com.deepin.wrap.gnome.desktop.background)" -ge 1 ]; then
     gsettings set com.deepin.wrap.gnome.desktop.background picture-uri "file://$WP"
+    if [[ "$4" =~ ^(wallpaper|centered|scaled|stretched|zoom|spanned)$ ]]; then
+        gsettings set com.deepin.wrap.gnome.desktop.background picture-options "$4"
+    fi
     if [ "$(gsettings get com.deepin.wrap.gnome.desktop.background picture-options)" == "'none'" ]; then
         gsettings set com.deepin.wrap.gnome.desktop.background picture-options 'zoom'
     fi
@@ -212,17 +217,18 @@ fi
 # Implementation note: this uses spaces around list items to enforce matching whole words.
 # This also means that an empty variable won't cause false positives, since it expands to "  "
 # FOR SDDM
-SIMPLE_WMS=("/usr/share/xsessions/awesome" "/usr/share/xsessions/bspwm" "/usr/share/xsessions/chadwm" "/usr/share/xsessions/cwm" "/usr/share/xsessions/dusk" "/usr/share/xsessions/dwm" "/usr/share/xsessions/fvwm3" "/usr/share/xsessions/herbstluftwm" "/usr/share/xsessions/hypr""/usr/share/xsessions/i3" "/usr/share/xsessions/i3-with-shmlog" "/usr/share/xsessions/icewm" "/usr/share/xsessions/icewm-session" "/usr/share/xsessions/jwm" "/usr/share/xsessions/leftwm" "/usr/share/xsessions/openbox" "/usr/share/xsessions/qtile" "/usr/share/xsessions/spectrwm" "/usr/share/xsessions/wmderland" "/usr/share/xsessions/xmonad")
+SIMPLE_WMS=("/usr/share/xsessions/awesome" "/usr/share/xsessions/bspwm" "/usr/share/xsessions/chadwm" "/usr/share/xsessions/cwm" "/usr/share/xsessions/dk" "/usr/share/xsessions/dusk" "/usr/share/xsessions/dwm" "/usr/share/xsessions/fvwm3" "/usr/share/xsessions/herbstluftwm" "/usr/share/xsessions/hypr""/usr/share/xsessions/i3" "/usr/share/xsessions/i3-with-shmlog" "/usr/share/xsessions/icewm" "/usr/share/xsessions/icewm-session" "/usr/share/xsessions/jwm" "/usr/share/xsessions/leftwm" "/usr/share/xsessions/openbox" "/usr/share/xsessions/qtile" "/usr/share/xsessions/spectrwm" "/usr/share/xsessions/wmderland" "/usr/share/xsessions/xmonad")
 if [[ " ${SIMPLE_WMS[*]} " = *" $XDG_CURRENT_DESKTOP "* || " ${SIMPLE_WMS[*]} " = *" $XDG_SESSION_DESKTOP "* ||
       " ${SIMPLE_WMS[*]} " = *" $DESKTOP_SESSION "* ]]; then
 	if command -v "feh" >/dev/null 2>&1; then
+	      # TODO: This should take the scaling parameter $4 into account and use other options than --bg-fill
         feh --bg-fill "$WP" 2> /dev/null
     elif command -v "nitrogen" >/dev/null 2>&1; then
         nitrogen --set-zoom-fill --save "$WP" 2> /dev/null
     fi
 fi
 #FOR LIGHTDM
-SIMPLE_WMS=("awesome" "berry" "bspwm" "chadwm" "cwm" "dusk" "dwm" "fvwm3" "herbstluftwm" "hypr" "i3" "i3-with-shmlog" "icewm" "icewm-session" "jwm" "leftwm" "openbox" "qtile" "spectrwm" "worm" "wmderland" "xmonad")
+SIMPLE_WMS=("awesome" "berry" "bspwm" "chadwm" "cwm" "dk" "dusk" "dwm" "fvwm3" "herbstluftwm" "hypr" "i3" "i3-with-shmlog" "icewm" "icewm-session" "jwm" "leftwm" "openbox" "qtile" "spectrwm" "worm" "wmderland" "xmonad")
 if [[ " ${SIMPLE_WMS[*]} " = *" $XDG_CURRENT_DESKTOP "* || " ${SIMPLE_WMS[*]} " = *" $XDG_SESSION_DESKTOP "* ||
       " ${SIMPLE_WMS[*]} " = *" $DESKTOP_SESSION "* ]]; then
     if command -v "feh" >/dev/null 2>&1; then
@@ -232,7 +238,7 @@ if [[ " ${SIMPLE_WMS[*]} " = *" $XDG_CURRENT_DESKTOP "* || " ${SIMPLE_WMS[*]} " 
     fi
 fi
 
-if [[ -n $SWAYSOCK ]]; then
+if [[ -n $SWAYSOCK || $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
     # If swaybg is available, use it as prevents system freeze.
     # See https://github.com/swaywm/sway/issues/5606
     if command -v "swaybg" >/dev/null 2>&1; then
@@ -257,11 +263,20 @@ fi
 
 # MATE after 1.6
 gsettings set org.mate.background picture-filename "$WP" 2> /dev/null
+if [ "$(gsettings get org.mate.desktop.background picture-options 2>/dev/null)" == "'none'" ]; then
+	gsettings set org.mate.desktop.background picture-options 'zoom'
+fi
+if [[ "$4" =~ ^(wallpaper|centered|scaled|stretched|zoom|spanned)$ ]]; then
+  gsettings set org.mate.desktop.background picture-options "$4"
+fi
 
 # Cinnamon after 2.0
 gsettings set org.cinnamon.desktop.background picture-uri "file://$WP" 2> /dev/null
 if [ "$(gsettings get org.cinnamon.desktop.background picture-options 2>/dev/null)" == "'none'" ]; then
 	gsettings set org.cinnamon.desktop.background picture-options 'zoom'
+fi
+if [[ "$4" =~ ^(wallpaper|centered|scaled|stretched|zoom|spanned)$ ]]; then
+  gsettings set org.cinnamon.desktop.background picture-options "$4"
 fi
 
 # Awesome Window Manager
@@ -269,7 +284,7 @@ fi
 # NOTE: This config will change the wallpaper after your current awesome theme sets it.
 # As such, the theme's wallpaper will briefly appear before being replaced with Variety's wallpaper.
 if [[ "$XDG_SESSION_DESKTOP $DESKTOP_STARTUP_ID $DESKTOP_SESSION $XDG_CURRENT_DESKTOP" == *"awesome"* ]]; then
-	echo "local gears = require(\"gears\") gears.wallpaper.maximized(\"$1\", nil)" | awesome-client
+	echo "for s in screen do require(\"gears\").wallpaper.maximized(\"$1\", s) end" | awesome-client
 fi
 
 # =====================================================================================
